name: travel_planner
description: "Smart travel planner with friends, voting, maps and chat"
#  Add Short  App intro

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

# Add New Packages :

  # Firebase 
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  firebase_database: ^12.4.1

  # State Manegment
  provider: ^6.1.5+1 

  # Map & Location
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_map_marker_cluster: ^8.2.2

  # Network & API 
  http: ^1.6.0
  cached_network_image: ^3.4.1
  dio: ^5.9.2

  # UI & UX
  shimmer: ^3.0.0
  lottie: ^3.3.3
  animations: ^2.2.0
  smooth_page_indicator: ^2.0.1
  photo_view: ^0.15.0
  carousel_slider: ^5.1.2
  flutter_slidable: ^4.0.3

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.3
  timeago: ^3.7.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  image_picker: ^1.2.2
  path_provider: ^2.1.5
  connectivity_plus: ^7.1.1

  # Date picker
  table_calendar: ^3.2.0
  syncfusion_flutter_datepicker: ^33.2.6
  
 



  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0


flutter:
   uses-material-design: true
   