name: genz_go
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.4.1
  connectivity_plus: ^7.1.1
  cupertino_icons: ^1.0.9
  dio: ^5.9.2
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_messaging: ^16.2.2
  firebase_storage: ^13.4.1
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  flutter_slidable: ^4.0.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.3.0
  fluttertoast: ^9.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  google_maps_flutter: ^2.17.0
  http: ^1.6.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.3
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  timeago: ^3.7.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

assets:
 - assets/screenshots/home.jpeg
 - assets/screenshots/expolre.jpeg
 - assets/screenshots/chat.jpeg
 - assets/screenshots/friend.jpeg
 - assets/screenshots/profile.jpeg