// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:768428763447:web:6de6c654fad6314d7952b2',
    messagingSenderId: '768428763447',
    projectId: 'genz-go',
    authDomain: 'genz-go.firebaseapp.com',
    storageBucket: 'genz-go.firebasestorage.app',
    measurementId: 'G-B0EEJPSVR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:768428763447:android:bcc84aa66c2bf0477952b2',
    messagingSenderId: '768428763447',
    projectId: 'genz-go',
    storageBucket: 'genz-go.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:768428763447:ios:9d3265709652cd217952b2',
    messagingSenderId: '768428763447',
    projectId: 'genz-go',
    storageBucket: 'genz-go.firebasestorage.app',
    iosBundleId: 'com.example.genzGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:768428763447:web:3f7b6716da4575197952b2',
    messagingSenderId: '768428763447',
    projectId: 'genz-go',
    authDomain: 'genz-go.firebaseapp.com',
    storageBucket: 'genz-go.firebasestorage.app',
    measurementId: 'G-V12LNBS2CD',
  );
}
